ingress:
  enabled: true
  className: "nginx" # Optional: Specify ingress class if needed (e.g., nginx)
  metadata:
    name: argocd-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - host: localhost
      paths:
        - path: /argo
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port: 
                name: https
  tls: [] # Leave empty since localhost doesn't use HTTPS/TLS
