ingress:
  enabled: true
  className: "" # Optional: Specify ingress class if needed (e.g., nginx)
  metadata:
    name: argocd-server-ingress
  namespace: argocd
  hosts:
    - host: localhost
      paths:
        - path: /argo
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port: 443
  tls: [] # Leave empty since localhost doesn't use HTTPS/TLS