ingress:
  enabled: true
  className: "" # Optional: Specify ingress class if needed (e.g., nginx)
  metadata:
    name: argocd-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Ensure HTTPS backend communication
    nginx.ingress.kubernetes.io/ssl-redirect: "false"    # Do not redirect HTTP to HTTPS for local testing
  hosts:
    - host: localhost
      paths:
        - path: /argo
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port: 443
  tls: [] # Leave empty since localhost doesn't use HTTPS/TLS